version: '2'
services:
    geste-app:
        image: geste
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://geste-mysql:3306/geste?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    geste-mysql:
        extends:
            file: mysql.yml
            service: geste-mysql
